name: SonarQube Cloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Or your specific Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Run tests and generate coverage
        run: |
          coverage run -m pytest 
          coverage xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          organization: 'speltriao'
          projectKey: 'fiap-video-processor'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}